pages:
  image: docker.io/debian:bookworm
  script:
    - apt-get update && apt-get install -y curl git libclang-dev clang pkg-config libssl-dev
    - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly"
    - source "$HOME/.cargo/env"
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-bindgen-cli
    - RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --target wasm32-unknown-unknown --release
    - wasm-bindgen target/wasm32-unknown-unknown/release/coap-ace-poc-webapp.wasm --out-dir public/ --web
    - 'sed "s/BUILDID/$(cat public/{index.html,*.css,coap-ace-poc*} | sha256sum | cut -f1 -d" ")/" < public/service_worker.js.in > public/service_worker.js'

    - RUSTFLAGS=--cfg=web_sys_unstable_apis cargo doc --target wasm32-unknown-unknown
    - cp -a target/wasm32-unknown-unknown/doc public/doc
  artifacts:
    paths:
      - public
