pages:
  image: docker.io/debian:bookworm
  script:
    # That libc6-dev-i386 fixes things indicates trouble somewhere else, but
    # things do pass tests with that.
    # Also, we need libclang-14-dev 1:14.0.6-9 (or one of the packages in its
    # version-locked cluster) to make use of that.
    - echo 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20221224 bookworm main' > /etc/apt/sources.list
    - apt-get update && apt-get install -y curl git libclang-dev clang libc6-dev-i386 pkg-config libssl-dev
    - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly"
    - source "$HOME/.cargo/env"
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-bindgen-cli
    - RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --target wasm32-unknown-unknown --release
    - wasm-bindgen target/wasm32-unknown-unknown/release/coap-ace-poc-webapp.wasm --out-dir public/ --web
    - 'sed "s/BUILDID/$(cat public/{index.html,*.css,coap-ace-poc*} | sha256sum | cut -f1 -d" ")/" < public/service_worker.js.in > public/service_worker.js'

    - RUSTFLAGS=--cfg=web_sys_unstable_apis cargo doc --target wasm32-unknown-unknown
    - cp -a target/wasm32-unknown-unknown/doc public/doc
  artifacts:
    paths:
      - public
