pages:
  image: rustdocker/rust:nightly
  script:
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-bindgen-cli
    - cargo build --target wasm32-unknown-unknown --release
    - wasm-bindgen target/wasm32-unknown-unknown/release/coap-ace-poc-webapp.wasm --out-dir public/ --web
  artifacts:
    paths:
      - public
