[package]
name = "coap-ace-poc-webapp"
version = "0.1.0"
edition = "2021"
authors = [ "EDF, developed in collaboration with Christian Amsüss" ]
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "^0.19.3"
console_error_panic_hook = "^0.1.7"
log = "^0.4"
console_log = "^0.2"
wasm-bindgen = "^0.2.83"
wasm-bindgen-futures = "^0.4.33"
js-sys = "^0.3.60"
web-sys = { version = "^0.3.60", features = [ "Navigator" , "Bluetooth", "RequestDeviceOptions", "BluetoothDevice", "BluetoothRemoteGattServer", "BluetoothRemoteGattService", "BluetoothRemoteGattCharacteristic", "BluetoothLeScanFilterInit"] }
